src/Entity/Images.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ImagesRepository::class)]
#[ApiResource]
class Images
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:list'])]
    private ?string $image_path = null;

    #[ORM\ManyToOne(targetEntity: Produits::class, inversedBy: 'images')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Produits $produit = null;

    private ?UploadedFile $file = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): self
    {
        $this->image_path = $image_path;
        return $this;
    }

    public function getProduit(): ?Produits
    {
        return $this->produit;
    }

    public function setProduit(?Produits $produit): self
    {
        $this->produit = $produit;
        return $this;
    }

    public function getFile(): ?UploadedFile
    {
        return $this->file;
    }

    public function setFile(?UploadedFile $file): self
    {
        $this->file = $file;
        return $this;
    }

    public function __toString(): string
    {
        return $this->image_path ?? 'Image';
    }
}

src/Entity/Produits.php
<?php

namespace App\Entity;

//Appel de la classe ApiResource
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;

use App\Repository\ProduitsRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;


#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
//Ajout de la directive ApiResource
#[ApiResource( operations: [ new GetCollection(normalizationContext: ['groups' => ['produits:list']]), new Get(normalizationContext: ['groups' => ['produits:detail']]), new Post(denormalizationContext: ['groups' => ['produits:write']]), new Put(denormalizationContext: ['groups' => ['produits:write']]), new Delete() ], )]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?string $produit_nom = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?string $produit_description = "" ?? null;

    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?float $produit_prix = 0 ?? null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?string $produit_slug = "" ?? null;

    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'produits', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:detail', 'produits:write'])]
    private ?References $reference = null;

    #[ORM\ManyToOne(inversedBy: 'produits', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:list', 'produits:write'])]
    private ?Categories $categorie = null;

    #[ORM\ManyToMany(targetEntity: Distributeurs::class, inversedBy: 'produits')]
    #[Groups(['produits:detail', 'produits:write'])]
    private Collection $distributeur;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Images::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[Groups(['produits:list', 'produits:write'])]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'produits', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:detail', 'produits:write'])]
    private ?User $user = null;

    /**
     * @var Collection<int, CommandeDetails>
     */
    #[ORM\OneToMany(targetEntity: CommandeDetails::class, mappedBy: 'produits')]
    #[Groups(['produits:detail'])]
    private Collection $commandeDetails;

    public function __construct()
    {
        $this->distributeur = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
        $this->updatedAt = new DateTimeImmutable();
        $this->commandeDetails = new ArrayCollection();
    }

    // --- Getters / Setters ---
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduitNom(): ?string
    {
        return $this->produit_nom;
    }

    public function setProduitNom(string $produit_nom): self
    {
        $this->produit_nom = $produit_nom;
        return $this;
    }

    public function getProduitDescription(): ?string
    {
        return $this->produit_description;
    }

    public function setProduitDescription(string $produit_description): self
    {
        $this->produit_description = $produit_description;
        return $this;
    }

    public function getProduitPrix(): ?float
    {
        return $this->produit_prix;
    }

    public function setProduitPrix(float $produit_prix): self
    {
        $this->produit_prix = $produit_prix;
        return $this;
    }

    public function getProduitSlug(): ?string
    {
        return $this->produit_slug;
    }

    public function setProduitSlug(string $produit_slug): self
    {
        $this->produit_slug = $produit_slug;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function getReference(): ?References
    {
        return $this->reference;
    }

    public function setReference(?References $reference): self
    {
        $this->reference = $reference;
        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): self
    {
        $this->categorie = $categorie;
        return $this;
    }

    public function getDistributeur(): Collection
    {
        return $this->distributeur;
    }

    public function addDistributeur(Distributeurs $distributeur): self
    {
        if (!$this->distributeur->contains($distributeur)) {
            $this->distributeur->add($distributeur);
        }
        return $this;
    }

    public function removeDistributeur(Distributeurs $distributeur): self
    {
        $this->distributeur->removeElement($distributeur);
        return $this;
    }

    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProduit($this);
        }
        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            if ($image->getProduit() === $this) {
                $image->setProduit(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    public function __toString(): string
    {
        return $this->produit_nom ?? 'Produit';
    }

    /**
     * @return Collection<int, CommandeDetails>
     */
    public function getCommandeDetails(): Collection
    {
        return $this->commandeDetails;
    }

    public function addCommandeDetail(CommandeDetails $commandeDetail): self
    {
        if (!$this->commandeDetails->contains($commandeDetail)) {
            $this->commandeDetails->add($commandeDetail);
            $commandeDetail->setProduits($this);
        }

        return $this;
    }

    public function removeCommandeDetail(CommandeDetails $commandeDetail): self
    {
        if ($this->commandeDetails->removeElement($commandeDetail)) {
            // set the owning side to null (unless already changed)
            if ($commandeDetail->getProduits() === $this) {
                $commandeDetail->setProduits(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Categories;
use App\Entity\Distributeurs;
use App\Entity\Produits;
use App\Entity\References;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('produit_nom')
            ->add('produit_description')
            ->add('produit_prix')
            ->add('produit_slug')
            ->add('createdAt', null, [
                'widget' => 'single_text',
            ])
            ->add('updatedAt', null, [
                'widget' => 'single_text',
            ])
            ->add('reference', EntityType::class, [
                'class' => References::class,
                'choice_label' => 'id',
            ])
            ->add('categorie', EntityType::class, [
                'class' => Categories::class,
                'choice_label' => 'id',
            ])
            ->add('distributeur', EntityType::class, [
                'class' => Distributeurs::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

src/Controller/ProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Form\ProduitsType;
use App\Repository\ProduitsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\SerializerInterface;

final class ProduitsController extends AbstractController
{
    #[Route('/produits', name: 'app_produits_index', methods: ['GET'])]
    public function index(ProduitsRepository $produitsRepository): Response
    {
        return $this->render('produits/index.html.twig', [
            'produits' => $produitsRepository->findAll(),
        ]);
    }

    #[Route('/produit/{id}', name: 'app_produits_show', methods: ['GET'])]
    public function show(Produits $produit): Response
    {
        return $this->render('produits/show.html.twig', [
            'produit' => $produit,
        ]);
    }
    #[Route('/produits/api', name: 'app_produits_api', methods: ['GET'])]
    public function productApi(
        ProduitsRepository $produitsRepository, //Acces au répository
        SerializerInterface $serializer //La classe de serialisation
    ):Response{
        $produits = $produitsRepository->findAll(); //Recuperer tous les produits dans une variables
        //Utilisé les methodes de la classe Serializer + format + le groupe concerné
        $produit_api = $serializer->serialize($produits, "json", ['groups' => ['produits:list']]);
        //Retourne une r"ponse au format Json
        return JsonResponse::fromJsonString($produit_api);
    }
}

templates/produits/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Afficher Produits
{% endblock %}

{% block body %}
    <div class="container shadow mt-5 p-3 bg-dark">
        <div class="text-center">
            <h2 class="text-warning">NOS PRODUITS</h2>
            <a href="{{ path('app_produits_api') }}" class="btn btn-warning mt-3">API</a>
        </div>
        <div class="row">
            {% for produit in produits %}
                <div class="col-md-3 col-sm-12 mt-5">
                    <div class="card h-100 mt-3 rounded">
                        <h5 class="text-info text-center">{{ produit.produitNom }}</h5>
                        <div class="p-3 rounded">
                            {% for image in produit.images %}
                                <img src="{{ asset('img/produits/' ~ image.imagePath) }}"
                                     title="{{ produit.produitNom }}"
                                     class="img-fluid mt-3" width="25%"
                                     alt="{{ produit.produitNom }}"/>
                            {% endfor %}
                        </div>
                        <div class="card-body">

                            <p class="text-success">
                                PRIX : {{ (produit.produitPrix / 100)|number_format(2, ',', ' ') }} €
                            </p>
                            <em class="text-warning">Propriétaire : {{ produit.user.email }}</em>
                            <a href="{{ path('app_produits_show', {id: produit.id}) }}" class="btn btn-warning mt-3">
                                Plus d'infos
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

templates/produits/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits{% endblock %}

{% block body %}
    <div class="container shadow mt-5">
        <h1>Détail du produit {{ produit.produitNom }}</h1>

        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>
                    {% for image in produit.images %}
                        <img src="{{ asset('img/produits/' ~ image.imagePath) }}"
                             title="{{ produit.produitNom }}"
                             class="img-fluid mt-3" width="25%"
                             alt="{{ produit.produitNom }}"/>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Produit_nom</th>
                <td>{{ produit.produitNom }}</td>
            </tr>
            <tr>
                <th>Produit_description</th>
                <td>{{ produit.produitDescription }}</td>
            </tr>
            <tr>
                <th>Produit_prix</th>
                <td>
                    <p class="text-success">
                        PRIX : {{ (produit.produitPrix / 100)|number_format(2, ',', ' ') }} €
                    </p>
                </td>
            </tr>
            <tr>
                <th>Produit_slug</th>
                <td>{{ produit.produitSlug }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ produit.createdAt ? produit.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ produit.updatedAt ? produit.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            </tbody>
        </table>

        <a class="btn btn-info" href="{{ path('app_produits_index') }}">Retour</a>
        <a class="btn btn-warning" href="{{ path('app_panier',{id: produit.id}) }}">Ajouter au panier</a>
    </div>
{% endblock %}