src/Entity/Commandes.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\CommandesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandesRepository::class)]
#[ApiResource]
class Commandes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_cmd = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $user = null;

    /**
     * @var Collection<int, CommandeDetails>
     */
    #[ORM\OneToMany(targetEntity: CommandeDetails::class, mappedBy: 'commandes', cascade:['persist', 'remove'])]
    private Collection $commandeDetails;

    /**
     * @var Collection<int, CommandeDetails>
     */
    #[ORM\OneToMany(targetEntity: CommandeDetails::class, mappedBy: 'commande')]
    private Collection $commande_detail;

    #[ORM\Column(length: 255)]
    private ?string $statut = null;

    public function __construct()
    {
        $this->commandeDetails = new ArrayCollection();
        $this->commande_detail = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroCmd(): ?string
    {
        return $this->numero_cmd;
    }

    public function setNumeroCmd(string $numero_cmd): self
    {
        $this->numero_cmd = $numero_cmd;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, CommandeDetails>
     */
    public function getCommandeDetails(): Collection
    {
        return $this->commandeDetails;
    }

    public function addCommandeDetail(CommandeDetails $commandeDetail): self
    {
        if (!$this->commandeDetails->contains($commandeDetail)) {
            $this->commandeDetails->add($commandeDetail);
            $commandeDetail->setCommandes($this);
        }

        return $this;
    }

    public function removeCommandeDetail(CommandeDetails $commandeDetail): self
    {
        if ($this->commandeDetails->removeElement($commandeDetail)) {
            // set the owning side to null (unless already changed)
            if ($commandeDetail->getCommandes() === $this) {
                $commandeDetail->setCommandes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommandeDetails>
     */
    public function getCommandeDetail(): Collection
    {
        return $this->commande_detail;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Entity/Produits.php
<?php

namespace App\Entity;

//Appel de la classe ApiResource
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;

use App\Repository\ProduitsRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;


#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
//Ajout de la directive ApiResource
#[ApiResource( operations: [ new GetCollection(normalizationContext: ['groups' => ['produits:list']]), new Get(normalizationContext: ['groups' => ['produits:detail']]), new Post(denormalizationContext: ['groups' => ['produits:write']]), new Put(denormalizationContext: ['groups' => ['produits:write']]), new Delete() ], )]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?string $produit_nom = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?string $produit_description = "" ?? null;

    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?float $produit_prix = 0 ?? null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:list', 'produits:detail', 'produits:write'])]
    private ?string $produit_slug = "" ?? null;

    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    #[Groups(['produits:list', 'produits:detail'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'produits', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:detail', 'produits:write'])]
    private ?References $reference = null;

    #[ORM\ManyToOne(inversedBy: 'produits', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:list', 'produits:write'])]
    private ?Categories $categorie = null;

    #[ORM\ManyToMany(targetEntity: Distributeurs::class, inversedBy: 'produits')]
    #[Groups(['produits:detail', 'produits:write'])]
    private Collection $distributeur;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Images::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[Groups(['produits:list', 'produits:write'])]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'produits', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:detail', 'produits:write'])]
    private ?User $user = null;

    /**
     * @var Collection<int, CommandeDetails>
     */
    #[ORM\OneToMany(targetEntity: CommandeDetails::class, mappedBy: 'produits')]
    #[Groups(['produits:detail'])]
    private Collection $commandeDetails;

    public function __construct()
    {
        $this->distributeur = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
        $this->updatedAt = new DateTimeImmutable();
        $this->commandeDetails = new ArrayCollection();
    }

    // --- Getters / Setters ---
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduitNom(): ?string
    {
        return $this->produit_nom;
    }

    public function setProduitNom(string $produit_nom): self
    {
        $this->produit_nom = $produit_nom;
        return $this;
    }

    public function getProduitDescription(): ?string
    {
        return $this->produit_description;
    }

    public function setProduitDescription(string $produit_description): self
    {
        $this->produit_description = $produit_description;
        return $this;
    }

    public function getProduitPrix(): ?float
    {
        return $this->produit_prix;
    }

    public function setProduitPrix(float $produit_prix): self
    {
        $this->produit_prix = $produit_prix;
        return $this;
    }

    public function getProduitSlug(): ?string
    {
        return $this->produit_slug;
    }

    public function setProduitSlug(string $produit_slug): self
    {
        $this->produit_slug = $produit_slug;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function getReference(): ?References
    {
        return $this->reference;
    }

    public function setReference(?References $reference): self
    {
        $this->reference = $reference;
        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): self
    {
        $this->categorie = $categorie;
        return $this;
    }

    public function getDistributeur(): Collection
    {
        return $this->distributeur;
    }

    public function addDistributeur(Distributeurs $distributeur): self
    {
        if (!$this->distributeur->contains($distributeur)) {
            $this->distributeur->add($distributeur);
        }
        return $this;
    }

    public function removeDistributeur(Distributeurs $distributeur): self
    {
        $this->distributeur->removeElement($distributeur);
        return $this;
    }

    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProduit($this);
        }
        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            if ($image->getProduit() === $this) {
                $image->setProduit(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    public function __toString(): string
    {
        return $this->produit_nom ?? 'Produit';
    }

    /**
     * @return Collection<int, CommandeDetails>
     */
    public function getCommandeDetails(): Collection
    {
        return $this->commandeDetails;
    }

    public function addCommandeDetail(CommandeDetails $commandeDetail): self
    {
        if (!$this->commandeDetails->contains($commandeDetail)) {
            $this->commandeDetails->add($commandeDetail);
            $commandeDetail->setProduits($this);
        }

        return $this;
    }

    public function removeCommandeDetail(CommandeDetails $commandeDetail): self
    {
        if ($this->commandeDetails->removeElement($commandeDetail)) {
            // set the owning side to null (unless already changed)
            if ($commandeDetail->getProduits() === $this) {
                $commandeDetail->setProduits(null);
            }
        }

        return $this;
    }
}

src/Controller/CommandesController.php
<?php


namespace App\Controller;


use App\Entity\CommandeDetails;
use App\Entity\Commandes;
use App\Entity\User;
use App\Repository\CommandeDetailsRepository;
use App\Repository\CommandesRepository;
use App\Repository\ProduitsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Validator\Constraints\Length;

class CommandesController extends AbstractController
{
    /**
     * @param SessionInterface $session
     * @param ProduitsRepository $produitsRepository
     * @param EntityManagerInterface $em
     * @return Response
     */
    #[Route('/commandes', name:'app_valider_commandes')]
    public function ajouterCommande(
        SessionInterface $session,
        ProduitsRepository $produitsRepository,
        EntityManagerInterface $em
    ):Response{
        //Imposer une connexion utilisateur
        $this->denyAccessUnlessGranted('ROLE_USER');
        //Récuperer le panier à l'aide de SessionInterface
        $panier = $session->get('panier', []);
        //Le panier n'est pas vide on creer la commande
        //Instance de l'entité Commandes
        $commande = new Commandes();
        //On remplit la commande à l'aide des setters
        //Utilisateur concerné
        $commande->setUser($this->getUser());
        //Numero de la commande => id randrom
        $commande->setNumeroCmd(uniqid());
        //Le statut de la commande
        $commande->setStatut("En attende de paiement");
        //Calcul du total
        $total = 0;
        //Parcous du panier par reférence pour les details de la commande
        foreach($panier as $item => $quantite){
            //Instance de l'entité CommandeDetails
            $commande_details = new CommandeDetails();
            $produit = $produitsRepository->find($item);
            //dd($produit);
            $prix = $produit->getProduitPrix();
            //Remplir les details de la commande
            $commande_details->setProduits($produit);
            $commande_details->setPrix($prix);
            $commande_details->setQuantite($quantite);
            //Ajout des details a la commande principale (parente)
            //Utilisation de la methode addCommandeDetails => genere par la relation OnToMany
            $commande->addCommandeDetail($commande_details);
        }

        $em->persist($commande);
        $em->flush();

        //On vide le panier
        $session->remove('panier');
        $this->addFlash('success', 'Votre commande à bien été validée !');
        return $this->redirectToRoute('app_resume_commande');
    }

    /**
     * @param CommandesRepository $commandesRepository
     * @param CommandeDetailsRepository $commandeDetailsRepository
     * @return Response
     */
    #[Route('/resume-commandes', name:'app_resume_commande')]
    public function resumeCommande(
        CommandesRepository $commandesRepository,
        CommandeDetailsRepository $commandeDetailsRepository
    ):Response{
        //Recuperer l'utilisateur connecté
        $user = $this->getUser();
        //Les commandes par l'utilisateur
        $commandes = $commandesRepository->findBy(['user' => $user]);
        //Tableau des details des commandes
        $details_commande = [];
        //Le total
        $total = 0;

        //Parcours des commandes de l'utilisateur connecté
        foreach ($commandes as $commande){
            $details = $commandeDetailsRepository->findBy(['commandes' => $commande]);
            //Remplir le tableau des details de la commande
            $details_commande[$commande->getId()] = $details;

            //Calculer le total
            foreach ($details as $detail){
                $total += $detail->getPrix() * $detail->getQuantite();
            }
        }
        return $this->render('commandes/resume_commande.html.twig',[
            'commandes' => $commandes,
            'details_commande' => $details_commande,
            'total' => $total,
            'statut' => $commande->getStatut()
        ]);
    }

    /**
     * @param Request $request
     * @param Commandes $commandes
     * @param EntityManagerInterface $em
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    #[Route('/supprimer-commandes/{id}', name:'app_supprimer_commande', methods:['POST'])]
    public function supprimerCommande(
        Request $request,
        Commandes $commandes,
        EntityManagerInterface $em
    ){
        if ($this->isCsrfTokenValid('delete' . $commandes->getId(), $request->getPayload()->get('_token'))) {
            $em->remove($commandes);
            $em->flush();
        }

        return $this->redirectToRoute('app_produits', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commandes/resume_commande.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container bg-dark shadow mt-5">
        {% if app.user.commandes|length > 0 %}
            <h2 class="text-center text-success">Détails des commande</h2>

            <div class="container shadow bg-dark">
                {% for commande in app.user.commandes %}

                    <div class="row bg-dark p-3 rounded shadow mt-3">
                        <div class="bg-dark p-3 mt-3 rounded">
                            <div class="text-center">
                                <h4 class="text-warning">
                                    Commande n° {{ commande.numeroCmd }}
                                </h4>
                                <h5 class="text-danger text-center">STATUT : {{ statut }}</h5>
                                <p class="text-primary">Votre email : {{ commande.user.email }}</p>
                                <p class="text-info">Date de la commande : {{ commande.createdAt|date('d/m/y') }}</p>
                                <div class="d-flex justify-content-center">
                                    <form method="post" action="{{ path('app_supprimer_commande', {'id': commande.id}) }}" onsubmit="return confirm('Confirmer la suppression de la commande ?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
                                        <button class="btn btn-danger mt-3">Annuler la commande</button>
                                    </form>

                                    <a href="{{path('app_paiement_stripe', {numero_cmd: commande.numeroCmd})}}" class="btn btn-success mt-3 mx-3">Payer via
                                        Stripe
                                    </a>

                                    <a href="" class="btn btn-info mt-3 mx-3">
                                        Exporter au format PDF
                                    </a>
                                    <a href="{{ path('app_produits_index') }}" class="btn btn-warning mt-3 mx-3">
                                        Retour à l'accueil
                                    </a>
                                </div>
                            </div>


                        </div>

                        {% for details in details_commande[commande.id] %}
                            <div class="col-md-3 col-sm-12">
                                <div class="card h-100">
                                    <div class="card-body text-center">
                                        <h4 class="text-info">{{ details.produits.produitNom }}</h4>
                                        <img src="img/produits{{ asset(details.produits.images[0]) }}" class="img-fluid" width="25%"
                                             alt="{{ details.produits.produitNom }}" title="{{ details.produits.produitNom }}" />
                                        <div class="text-info">Quantité(s) : {{ details.quantite }}</div>

                                        <h5 class="text-success mt-3">Prix : {{ (details.prix / 100)|number_format(2, ',', ' ') }} €</h5>
                                        {% set montant_total = details.prix * details.quantite %}
                                        <hr>
                                        <h4 class="text-warning">Sous-total : {{ (montant_total / 100)|number_format(2, ',', ' ') }} €</h4>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <h2 class="bg-warning p-3 text-white mt-3">TOTAL DE LA COMMANDE : {{ (total / 100)|number_format(2, ',', ' ') }} €</h2>
        {% else %}
            <div class="alert alert-danger mt-5">
                <div class="p-3">
                    <h4 class="text-warning">Vous n'avez aucune commande !</h4>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}